//...
const express = require("express"); //importing the expresss module...
const router = express.Router(); //getting the instance of the router...

//defining a basic route/endpoint ('/')...
router.get("/", (req, res) => {
  res.send("Hello World!!!"); //sends hello world as the response for request of '/' endpoint...
});

//exporting the routes...
module.exports = router;
